### ISSUE TITLE
tool is not working for g512 se

### ISSUE THREAD

**Issue by betasve** [MatMoul/g810-led-wireshark-dump#5]
Hello, 

I've just recently bought a g512 se and I am now looking into how to deal with led backlight. Unfortunately I was not able to do that using your tool. 

I think I've tried all of the options I was able to find, with or without `sudo`. Also found the instructions on testing unsupported hardware (with the device and product ids and `-tuk`). Still no progress. 

The next thing I've found is the dumps library. I'm willing to try and make a dump of the keyboard but I am not sure how to do that. Google wasn't helpful as well. Could you please give me a hint and I will try and provide such a dump. 

Thanks in advance for yor support.

**Comment by TheoDps** [comment]
It seems that someone is already on it https://github.com/MatMoul/g810-led/pull/197

edit: I didn't see it before but there's also an issue opened for this keyboard here :wink: https://github.com/MatMoul/g810-led/issues/200

**Comment by betasve** [comment]
Great! Thanks for the timely response. I will try with the mentioned fork tomorrow and will update my issue accordingly. 

Regards,
Svetoslav

**Comment by betasve** [comment]
The one you've pointed out work like a charm, thanks a lot! :)
